# Run keepalived using host mode, which allows the container to share the host's network stack. This is useful for keepalived as it needs to manage virtual IPs and interact with the network interfaces directly.
services:
  keepalived:
    build:
      context: .
      dockerfile: Dockerfile.armv7
    image: ${KA_IMAGE}
    container_name: ${KA_CONTAINER_NAME:-keepalived}
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    # Define the healthcheck to perform.
    healthcheck:
      test: ["CMD-SHELL", ${HEALTHCHECK_CMD:-nslookup google.com}]
      interval: ${HEALTHCHECK_INT:-30s}
      timeout: ${HEALTHCHECK_TOT:-10s}
      retries: ${HEALTHCHECK_RTS:-3}
      start_period: ${HEALTHCHECK_STP:-30s}
    # Joins the network namespace
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${KA_CFG:-./vol/keepalived.conf}:/usr/local/etc/keepalived/keepalived.conf:ro
