services:
  keepalived:
    build:
      context: .
      dockerfile: Dockerfile.armv7
    image: ${KA_IMAGE}
    container_name: ${KA_CONTAINER_NAME:-keepalived}
    restart: always
    # Load variables from env file and pass explicit runtime envs to container
    # env_file:
    #   - ./secrets/keepalived/docker-01.env
    environment:
      KEEPALIVED_OPTS: "${KEEPALIVED_OPTS:--n -l -D -f /usr/local/etc/keepalived/keepalived.conf}"
      KEEPALIVED_LOG_FILE: "${KEEPALIVED_LOG_FILE:-/var/log/keepalived/keepalived.log}"
      LOGROTATE_INTERVAL: "${LOGROTATE_INTERVAL:-86400}"
      LOGROTATE_ROTATE: "${LOGROTATE_ROTATE:-7}"
      LOGROTATE_COMPRESS: "${LOGROTATE_COMPRESS:-true}"
    # Define the healthcheck to perform.
    healthcheck:
      test:
        - "CMD-SHELL"
        - ${HEALTHCHECK_CMD:-nslookup google.com}
      interval: ${HEALTHCHECK_INT:-30s}
      timeout: ${HEALTHCHECK_TOT:-10s}
      retries: ${HEALTHCHECK_RTS:-3}
      start_period: ${HEALTHCHECK_STP:-30s}
    # Joins the network namespace
    networks:
      shared_bridge:  
        labels:
          com.docker.network.endpoint.ifname: ${KA_BRIDGE_ETH:-eth-shared}
      vlan010_net:
        ipv4_address: ${KA_VLAN010}
        labels:
          com.docker.network.endpoint.ifname: ${KA_VLAN010_ETH:-eth-010}
      vlan100_net:
        ipv4_address: ${KA_VLAN100}
        labels:
          com.docker.network.endpoint.ifname: ${KA_VLAN100_ETH:-eth-100}
      vlan200_net:
        ipv4_address: ${KA_VLAN200}
        labels:
          com.docker.network.endpoint.ifname: ${KA_VLAN200_ETH:-eth-200}
      # vlan400_net:
      #   ipv4_address: ${KA_VLAN400}
      #   labels:
      #     com.docker.network.endpoint.ifname: ${KA_VLAN400_ETH:-eth-400}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    volumes:
      - ${KA_VOL_CFG:-./vol/keepalived.conf}:/usr/local/etc/keepalived/keepalived.conf:ro
      - ${KA_VOL_LOG:-./vol/log/}:/var/log/keepalived/:rw

networks:
  shared_bridge:
    name: ${BRIDGE_NAME}
    external: true
  vlan010_net:
    name: ${VLAN010_NAME}
    external: true
  vlan100_net:
    name: ${VLAN100_NAME}
    external: true
  vlan200_net:
    name: ${VLAN200_NAME}
    external: true
  # vlan400_net:
  #   name: ${VLAN400_NAME}
  #   external: true